apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: simple-nodejs-app-jho0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qewe-tenant/nodejs-users/simple-nodejs-app-jho0@sha256:014f2f81d5bdfd387c853c1b48ead3f028a75bd2e0c6a2cd054141e7c43874db
        name: my-nodejs
        resources: {}
status: {}
